version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Installing Dependencies
          command: npm install

      - run:
          name: installing gulp
          command: sudo npm install gulp-cli -g

      - run:
          name: installing gulp
          command: npm install gulp -D

      - run:
          name: installing gulp
          command: sudo npm install -g npx

      - run:
          name: installing gulp
          command: npx -p touch nodetouch gulpfile.js

      - run:
          name: Building
          command: gulp

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:  
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Installing Dependencies
          command: npm install

      - run:
          name: installing gulp
          command: sudo npm install gulp-cli -g

      - run:
          name: installing gulp
          command: npm install gulp -D

      - run:
          name: installing gulp
          command: sudo npm install -g npx

      - run:
          name: installing gulp
          command: npx -p touch nodetouch gulpfile.js

      - run:
          name: Building
          command: gulp

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Installing pip
          command: sudo apt-get install python-pip python-dev build-essential 
      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Show files
          command: ls -al

      - run:
          name: Deploy to S3
          command: aws s3 sync . s3://www.ccnurseryschool.ca/ --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
