version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Installing Dependencies
          command: npm install

      - run:
          name: installing gulp
          command: sudo npm install gulp-cli -g

      - run:
          name: installing gulp
          command: npm install gulp -D

      - run:
          name: installing gulp
          command: sudo npm install -g npx

      - run:
          name: installing gulp
          command: npx -p touch nodetouch gulpfile.js

      - run:
          name: Building
          command: gulp

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:  
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Installing Dependencies
          command: npm install

      - run:
          name: installing gulp
          command: sudo npm install gulp-cli -g

      - run:
          name: installing gulp
          command: npm install gulp -D

      - run:
          name: installing gulp
          command: sudo npm install -g npx

      - run:
          name: installing gulp
          command: npx -p touch nodetouch gulpfile.js

      - run:
          name: Building
          command: gulp

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - aws-s3/sync:
          from: .
          to: s3://www.ccnurseryschool.ca
          arguments:
            --exclude ".circleci/*" 


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
